version: "3"

services:
  workspace:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: .
    volumes:
      - ./:/workspace:cached
    ports: []
    depends_on:
      - "cosmosdb"

    command: /bin/sh -c "while sleep 1000; do :; done"

  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports:
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
    volumes:
      - "cosmosdb:/tmp/cosmos/appdata/"
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: "3"
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"

volumes:
  cosmosdb: {}
